import assert from 'node:assert/strict';
import test from 'node:test';
import { readFileSync } from 'node:fs';

function read(path: string) {
  return readFileSync(new URL(`../${path}`, import.meta.url), 'utf8');
}

test('admin routes expose support workspace and safe lifecycle controls', () => {
  const adminHome = read('app/admin/page.tsx');
  const adminDetail = read('app/admin/[businessId]/page.tsx');
  const activityTimeline = read('components/admin-business-activity-timeline.tsx');
  const stepCard = read('components/admin-business-setup-step-card.tsx');
  const supportWorkspace = read('app/admin/[businessId]/workspace/page.tsx');
  const adminActions = read('app/admin/actions.ts');
  const businessPicker = read('components/admin-business-picker.tsx');
  const founderDeleteCard = read('components/founder-delete-business-card.tsx');
  const appLayout = read('app/app/layout.tsx');

  assert.match(adminHome, /Operator control panel/);
  assert.match(adminHome, /Create new business/);
  assert.match(adminHome, /Create business workspace/);
  assert.match(adminHome, /Advanced founder tools/);
  assert.match(adminHome, /Delete one test\/demo business/);
  assert.match(adminHome, /Advanced founder reset: delete all current businesses/);
  assert.match(founderDeleteCard, /Delete this business/);
  assert.match(founderDeleteCard, /Type the exact business name/);
  assert.match(adminHome, /FOUNDER_DELETE_ALL_BUSINESSES_CONFIRMATION/);
  assert.match(adminHome, /Business triage board/);
  assert.match(adminHome, /Current reason/);
  assert.match(adminHome, /Next action/);
  assert.match(adminHome, /Open customer workspace/);
  assert.match(adminHome, /Delete demo\/test business permanently/);
  assert.match(adminHome, /Type business name to permanently delete/);
  assert.match(adminHome, /Open customer leads/);
  assert.match(adminActions, /export async function founderDeleteAllBusinessesAction/);
  assert.match(adminActions, /export async function saveAdminTwilioSetupAction/);
  assert.match(adminActions, /export async function saveAdminSetupBasicsAction/);
  assert.match(adminActions, /export async function createBusinessTwilioSubaccountAction/);
  assert.match(adminActions, /export async function createBusinessMessagingServiceAction/);
  assert.match(adminActions, /export async function confirmMissedCallValidationAction/);
  assert.match(adminActions, /export async function markBusinessLiveAction/);
  assert.match(adminActions, /getOptionalTwilioSidError/);
  assert.match(adminActions, /getMessagingComplianceSidValidationError/);
  assert.match(adminActions, /const admin = await requireAdmin\(\)/);
  assert.match(adminHome, /View support workspace snapshot/);
  assert.match(businessPicker, /Jump to business/);
  assert.match(businessPicker, /Clear selection/);
  assert.match(adminDetail, /setup control panel/);
  assert.match(adminDetail, /automatic repair and manual fallback/i);
  assert.match(adminDetail, /Setup steps/);
  assert.match(adminDetail, /Last issue/);
  assert.match(adminDetail, /Open fix step/);
  assert.match(adminDetail, /Test SMS truth/);
  assert.match(adminDetail, /Onboarding confidence/);
  assert.match(adminDetail, /Next step/);
  assert.match(adminDetail, /Mark business live/);
  assert.match(adminDetail, /Mark missed-call flow validated/);
  assert.match(adminDetail, /Mark live with warnings/);
  assert.match(adminDetail, /Advanced/);
  assert.match(adminDetail, /Invite owner by email/);
  assert.match(adminDetail, /Connect existing owner/);
  assert.match(adminDetail, /Send test SMS/);
  assert.match(stepCard, /Manual fallback \/ manual entry/);
  assert.match(stepCard, /Latest evidence/);
  assert.match(stepCard, /Warnings before completion/);
  assert.match(stepCard, /Step-by-step/);
  assert.match(stepCard, /How to verify/);
  assert.match(adminDetail, /Create subaccount automatically/);
  assert.match(adminDetail, /Create Messaging Service automatically/);
  assert.match(adminDetail, /Re-sync status callback/);
  assert.match(adminDetail, /Open customer settings/);
  assert.match(adminDetail, /Open customer call flow/);
  assert.match(adminDetail, /View support workspace snapshot/);
  assert.match(adminDetail, /canDeleteTestBusiness\(business\)/);
  assert.match(adminDetail, /getDeleteTestBusinessBlockedReason\(business\)/);
  assert.match(adminHome, /Restore business/);
  assert.match(activityTimeline, /Recent activity/);
  assert.match(activityTimeline, /Show more activity/);
  assert.match(activityTimeline, /Collapse activity/);
  assert.match(activityTimeline, /Expand details/);
  assert.doesNotMatch(adminDetail, /Connect or invite owner/);
  assert.match(supportWorkspace, /support mode workspace/);
  assert.match(supportWorkspace, /Open customer workspace/);
  assert.match(supportWorkspace, /View leads snapshot/);
  assert.match(supportWorkspace, /View settings snapshot/);
  assert.match(supportWorkspace, /View call flow snapshot/);
  assert.match(supportWorkspace, /Customer settings snapshot/);
  assert.match(supportWorkspace, /Customer call flow snapshot/);
  assert.match(appLayout, /Admin customer mode/);
  assert.match(appLayout, /Exit customer mode/);
});
